# Netscape HTTP Cookie File
# https://curl.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

.tiket.com	TRUE	/	FALSE	0	userlang	id
.tiket.com	TRUE	/	FALSE	0	device	desktop
.tiket.com	TRUE	/	FALSE	0	_tix_logger_correlation_id	d3f90b60-592d-4730-a848-dc6d34e087d9
#HttpOnly_.tiket.com	TRUE	/	FALSE	1694604494	session_access_token	eyJraWQiOiJiZjlvU0twQnpDNTlyc3lrVDhMWDBmYzlpSGExRmZhYyJ9.eyJhdWQiOiJ0aWtldC5jb20iLCJzdWIiOiI2NGVkZDY0ZTIyYmNiOTIwNDVlMDkxNjEiLCJuYmYiOjE2OTMzMDg0OTQsImlzcyI6Imh0dHBzOi8vd3d3LnRpa2V0LmNvbSIsImV4cCI6MTcwOTA4ODQ5NH0.z656IA7p0t-oM4zAVM3idJMqAt9ty00-gckoouWz9HEdJBFChHF8EuSbS1xRBMSO
#HttpOnly_.tiket.com	TRUE	/	FALSE	1694604494	session_refresh_token	eyJraWQiOiJMWHlIVDhzOG94aGhmUXNzTmNwbmJ6NUdVSEJUeDVwTCJ9.eyJhdWQiOiJ0aWtldC5jb20vcnQiLCJzdWIiOiI2NGVkZDY0ZTIyYmNiOTIwNDVlMDkxNjEiLCJuYmYiOjE2OTMzMDg0OTQsImlzcyI6Imh0dHBzOi8vd3d3LnRpa2V0LmNvbSIsImV4cCI6MTcyNDg2ODQ5NH0.ZDGA181JKO_YGo-mzrr6c7OmnfWSVaWUIqZmYmVj7atC6azt0eA7QCTqQeaHd9sx
.tiket.com	TRUE	/	FALSE	0	PHPSESSID	ca6483c4-82ea-4a91-bd76-d5c68db4a40f
#HttpOnly_.tiket.com	TRUE	/	TRUE	1693310294	__cf_bm	oQO7cP1fUWT4.91NFi1BpO0S3eApcq8pRokzpv2JaRU-1693308494-0-AX2naH94hwBY5z0Tx/ZxLY5iu/Gck933jv5C6GvEpUdMsJYSlfewxGHBz+liTkcbeGwUhUaZQhfzsCuI8cmYhMGISrBzF2LM4VXzQTXAdFiz
#HttpOnly_.tiket.com	TRUE	/	TRUE	0	_cfuvid	E.UGXIDpOwsRllD27WN8OgzdbPHoGN_s.Zxbf6mkaxw-1693308494911-0-604800000
